#!/usr/bin/env bash
# Install nginx web server
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Install firewall
sudo ufw app list
# Listen port 80
sudo ufw allow 'Nginx HTTP'
# change index webpage
echo "Hello World" | sudo tee /var/www/htm/index.nginx-debian.html
#restart
sudo systemctl restart nginx
