#!/usr/bin/env bash
# Install nginx web server
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
# Install firewall
sudo ufw app list
# Listen port 80
sudo ufw allow 'Nginx HTTP'
# change index webpage
echo "Hello World" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
# Redicetions
to_append='\\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
search='server_name\ _;'
file_path='/etc/nginx/sites-available/default'
sudo sed -i "/$search/a $to_append" $file_path

# for error 404
error_append='\\terror_page 404 /error404.html;'
sudo sed -i "/$search/a $error_append" $file_path

#restart
sudo service nginx restart
