#!/usr/bin/env bash
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task
#initialize variables
search='location \/ {'
file_path='/etc/nginx/sites-available/default'
to_append="add_header X-Served-By $HOSTNAME;"
# sed command to find and append the string
sudo sed -i "/$search/a $to_append" $file_path
# restart
sudo service nginx restart
