#!/usr/bin/env bash
# Write a Bash script that displays the PID, along with the process name,
# of processes whose name contain the word bash.
# shellcheck disable=SC2009

lines="$(pidof bash)"

for line in $lines
do
    echo "$line bash"
done
