#!/usr/bin/env bash
# Function with for while and in 9th line print Hi
i=0
while [ $i -lt 10 ]
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else
    echo "Best School"
    fi
    ((i++))
done
