#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

# Requirements:

#     You must use if and, else (case is forbidden)
#     Your Bash script should check if the file exists and print:
#         if the file exists: school file exists
#         if the file does not exist: school file does not exist
#     If the file exists, print:
#         if the file is empty: school file is empty
#         if the file is not empty: school file is not empty
#         if the file is a regular file: school is a regular file
#         if the file is not a regular file: (nothing)

filename="school"
#file exists
if [ -e "$filename" ]
then
    echo "$filename file exists"

    #Empty
    if [ -s "$filename" ]
    then
        echo "$filename file is empty"
    
    else
        echo "$filename file is not empty"
    fi
    
    if [ -f "$filename" ]
    then
        echo "$filename is a regular file"
    fi
#file does not exist
else
    echo "$filename file does not exist"
fi
