#!/usr/bin/env bash
# config user Nginx

# realse port 8080
sudo pkill -9 apache2
# variable with path to change user
user_change="/etc/nginx/nginx.conf";
# remove permissions of execution
sudo chmod 644 $user_change
# change user
user_new="user nginx;";
sed -i "s|#user www-data;|$user_new|" $user_change
# variable with path to change port for listening the port 8080
path="/etc/nginx/sites-available/default";
# change port 80 to 8080
sed -i "s|80 default_server|8080 default_server|" $path
# restar service with new user Ngninx
sudo -u nginx service nginx start
